function json(data, status = 200) {
  return Response.json(data, {
    status,
    headers: {
      'Cache-Control': 'no-store',
    },
  })
}

const nativeApps = [
  {
    id: 'takeoff-editor',
    name: 'TakeOff Editor',
    description: 'Editor visuale centrale per costruire pagine, sezioni e contenuti del sito.',
    status: 'active',
    status_label: 'Active',
    category: 'Core',
    open_hash: '#editor',
    badge: 'Native app',
  },
  {
    id: 'takeoff-media-library',
    name: 'TakeOff Media Library',
    description: 'Libreria visuale per upload, URL fallback, anteprime, filtri e alt text.',
    status: 'configurable',
    status_label: 'Configurable',
    category: 'Core',
    open_hash: '#media',
    badge: 'Native app',
  },
  {
    id: 'takeoff-import-export',
    name: 'TakeOff Import Export Pro',
    description: 'Importa, esporta, aggiorna stock e prepara translation package senza app esterne.',
    status: 'active',
    status_label: 'Active',
    category: 'Core',
    open_hash: '#import-export',
    badge: 'Native app',
  },
  {
    id: 'takeoff-translate',
    name: 'TakeOff Translate',
    description: 'Gestione traduzioni contenuti pubblici con fallback alla lingua originale.',
    status: 'configurable',
    status_label: 'Configurable',
    category: 'Core',
    open_hash: '#traduzioni',
    badge: 'Native app',
  },
  {
    id: 'takeoff-markets',
    name: 'TakeOff Markets',
    description: 'Mercati, lingue, valute e pricing localizzato con fallback sicuri.',
    status: 'configurable',
    status_label: 'Configurable',
    category: 'Core',
    open_hash: '#markets',
    badge: 'Native app',
  },
  {
    id: 'takeoff-seo',
    name: 'TakeOff SEO',
    description: 'Dashboard SEO centrale per metadati, snippet preview, contenuti mancanti e suggerimenti.',
    status: 'configurable',
    status_label: 'Configurable',
    category: 'Core',
    open_hash: '#seo',
    badge: 'Native app',
  },
  {
    id: 'takeoff-orders',
    name: 'TakeOff Orders',
    description: 'Order Management Pro con stati, timeline, note, pagamento manuale e fulfillment operativo.',
    status: 'active',
    status_label: 'Active',
    category: 'Commerce',
    open_hash: '#ordini',
    badge: 'Native app',
  },
  {
    id: 'takeoff-checkout',
    name: 'TakeOff Checkout',
    description: 'Checkout, pagamento manual/test e struttura pronta per provider esterni.',
    status: 'configurable',
    status_label: 'Configurable',
    category: 'Commerce',
    open_hash: '#checkout',
    badge: 'Native app',
  },
  {
    id: 'takeoff-shipping-rules',
    name: 'TakeOff Shipping Rules',
    description: 'Metodi, soglie gratuite e regole base per market/country senza corrieri esterni.',
    status: 'configurable',
    status_label: 'Configurable',
    category: 'Commerce',
    open_hash: '#shipping',
    badge: 'Native app',
  },
  {
    id: 'takeoff-customer-accounts',
    name: 'TakeOff Customer Accounts',
    description: 'Account status, inviti mock/provider-ready, lifetime value e storico ordini cliente.',
    status: 'base_config',
    status_label: 'Basic configuration',
    category: 'Commerce',
    open_hash: '#clienti',
    badge: 'Native app',
  },
  {
    id: 'takeoff-returns',
    name: 'TakeOff Returns',
    description: 'Gestione resi e rimborsi manuali con workflow operativo e template email collegati.',
    status: 'base_config',
    status_label: 'Basic configuration',
    category: 'Commerce',
    open_hash: '#returns',
    badge: 'Native app',
  },
  {
    id: 'takeoff-reviews',
    name: 'TakeOff Reviews',
    description: 'Recensioni prodotto native con moderazione, rating medio e widget storefront.',
    status: 'configurable',
    status_label: 'Configurable',
    category: 'Commerce',
    open_hash: '#reviews',
    badge: 'Native app',
  },
  {
    id: 'takeoff-upsells',
    name: 'TakeOff Upsell & Bundles',
    description: 'Bundle, frequently bought together e cart upsell con fallback puliti.',
    status: 'base_config',
    status_label: 'Basic configuration',
    category: 'Commerce',
    open_hash: '#upsells',
    badge: 'Native app',
  },
  {
    id: 'takeoff-analytics',
    name: 'TakeOff Analytics',
    description: 'Overview, traffico, vendite, prodotti, conversioni ed eventi raccolti dal CMS.',
    status: 'configurable',
    status_label: 'Configurable',
    category: 'Growth',
    open_hash: '#analisi',
    badge: 'Native app',
  },
  {
    id: 'takeoff-google-suite',
    name: 'TakeOff Google Suite',
    description: 'Collega GA4, Google Ads, Search Console e Tag Manager senza salvare secrets.',
    status: 'configurable',
    status_label: 'Requires external configuration',
    category: 'Growth',
    open_hash: '#google-suite',
    badge: 'Native app',
  },
  {
    id: 'takeoff-email-automations',
    name: 'TakeOff Email Automations',
    description: 'Template e log email provider-ready per ordini, resi, customer flow e newsletter.',
    status: 'base_config',
    status_label: 'Requires external configuration',
    category: 'Growth',
    open_hash: '#email-automations',
    badge: 'Native app',
  },
  {
    id: 'takeoff-product-feed',
    name: 'TakeOff Product Feed',
    description: 'Feed Google Merchant e Meta Catalog in XML/CSV senza integrazioni esterne obbligatorie.',
    status: 'configurable',
    status_label: 'Configurable',
    category: 'Growth',
    open_hash: '#product-feeds',
    badge: 'Native app',
  },
  {
    id: 'takeoff-marketing',
    name: 'TakeOff Marketing',
    description: 'Campagne, sconti e strumenti promozionali integrati nel CMS.',
    status: 'base_config',
    status_label: 'Basic configuration',
    category: 'Growth',
    open_hash: '#marketing',
    badge: 'Native app',
  },
  {
    id: 'takeoff-backup',
    name: 'TakeOff Backup',
    description: 'Export backup completo JSON e restore controllato tramite strumenti di import.',
    status: 'active',
    status_label: 'Active',
    category: 'System',
    open_hash: '#backup',
    badge: 'Native app',
  },
  {
    id: 'takeoff-store-health',
    name: 'TakeOff Store Health',
    description: 'Centro salute store con API, database, checkout, provider, backup e configurazioni lancio.',
    status: 'active',
    status_label: 'Active',
    category: 'System',
    open_hash: '#store-health',
    badge: 'Native app',
  },
  {
    id: 'takeoff-launch-checklist',
    name: 'TakeOff Launch Checklist',
    description: 'Checklist go-live calcolata automaticamente per contenuti, checkout, privacy, dominio e backup.',
    status: 'active',
    status_label: 'Active',
    category: 'System',
    open_hash: '#launch-checklist',
    badge: 'Native app',
  },
  {
    id: 'takeoff-gdpr-cookie',
    name: 'TakeOff GDPR / Cookie',
    description: 'Cookie categories, Google Consent Mode base e strumenti privacy provider-ready.',
    status: 'base_config',
    status_label: 'Basic configuration',
    category: 'System',
    open_hash: '#gdpr-cookie',
    badge: 'Native app',
  },
  {
    id: 'takeoff-integrations',
    name: 'TakeOff Integrations',
    description: 'Integrazioni e webhook non sensibili gestiti dal pannello.',
    status: 'base_config',
    status_label: 'Basic configuration',
    category: 'System',
    open_hash: '#integrazioni',
    badge: 'Native app',
  },
  {
    id: 'takeoff-3d-viewer',
    name: 'TakeOff 3D Viewer',
    description: 'Viewer prodotto 3D nativo per esperienze digitali premium.',
    status: 'configurable',
    status_label: 'Configurable',
    category: 'System',
    open_hash: '#editor',
    badge: 'Native app',
  },
]

export async function onRequestGet() {
  return json({
    success: true,
    apps: nativeApps,
  })
}
