function xml(value) {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function tableMissing(error) {
  return String(error && error.message ? error.message : error || "").toLowerCase().includes("no such table");
}

async function loadFeedSettings(env) {
  try {
    const row = await env.DB.prepare("SELECT * FROM product_feed_settings WHERE provider = 'google' LIMIT 1").first();
    return row || { active: 0, title: "TakeOff Google Merchant Feed", default_currency: "EUR", include_out_of_stock: 0 };
  } catch (error) {
    if (tableMissing(error)) return { active: 0, title: "TakeOff Google Merchant Feed", default_currency: "EUR", include_out_of_stock: 0 };
    throw error;
  }
}

function priceValue(product) {
  const cents = Number(product.localized_price_cents ?? product.price_cents ?? product.price ?? 0);
  if (cents > 1000) return cents / 100;
  return cents;
}

export async function onRequestGet({ env, request }) {
  try {
    const url = new URL(request.url);
    const origin = url.origin;
    const settings = await loadFeedSettings(env);
    const includeOutOfStock = Number(settings.include_out_of_stock) === 1;

    const rows = await env.DB.prepare(
      `
        SELECT id, name, slug, description, image_url, price_cents, stock
        FROM products
        WHERE (? = 1 OR COALESCE(stock, 0) > 0)
        ORDER BY id DESC
        LIMIT 1000
      `,
    )
      .bind(includeOutOfStock ? 1 : 0)
      .all();

    const products = rows.results || [];
    const items = products
      .map((product) => {
        const title = product.name || `Product ${product.id}`;
        const link = `${origin}/products/${encodeURIComponent(product.slug || product.id)}`;
        const price = `${priceValue(product).toFixed(2)} ${settings.default_currency || "EUR"}`;
        const availability = Number(product.stock || 0) > 0 ? "in stock" : "out of stock";

        return `
          <item>
            <g:id>${xml(product.id)}</g:id>
            <g:title>${xml(title)}</g:title>
            <g:description>${xml(product.description || title)}</g:description>
            <g:link>${xml(link)}</g:link>
            <g:image_link>${xml(product.image_url || "")}</g:image_link>
            <g:price>${xml(price)}</g:price>
            <g:availability>${xml(availability)}</g:availability>
            <g:condition>new</g:condition>
          </item>`;
      })
      .join("");

    const feed = `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:g="http://base.google.com/ns/1.0">
  <channel>
    <title>${xml(settings.title || "TakeOff Google Merchant Feed")}</title>
    <link>${xml(origin)}</link>
    <description>${xml("Product feed generated by TakeOffMilan CMS")}</description>
    ${items}
  </channel>
</rss>`;

    return new Response(feed, {
      headers: {
        "content-type": "application/xml; charset=utf-8",
        "cache-control": "public, max-age=300",
      },
    });
  } catch {
    return new Response(`<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>Product feed unavailable</title></channel></rss>`, {
      headers: {
        "content-type": "application/xml; charset=utf-8",
        "cache-control": "public, max-age=60",
      },
    });
  }
}
